### ISSUE TITLE
How to start?

### ISSUE THREAD

**Issue by kreidlerflorett** [Eluinhost/teamspeak-channel-creator#3]
Hello,

I found this bot but I don't have an idea how to start.
Could you please help me? :D

**Comment by Eluinhost** [comment]
Assuming you have node already installed you can run 'node .' inside a folder to start a node app. I prefer to use Forever (https://github.com/foreverjs/forever) which you install via 'npm install -g forever' and can then start it running in the background by running 'forever start .' when in the folder

**Comment by LuisS2301** [comment]
If I type "node index.js" in the folder this error occured: 

/opt/teamspeak-channel/index.js:7
t createClosestChannel = (bot, parentId, username, password, maxAttempts) => {
                                                                           ^
SyntaxError: Unexpected token >
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3

If I type node nothing happens.

**Comment by Eluinhost** [comment]
You're running an older node version, this is using ES6 syntax. You should be safe on anything > node 6.0. If you're running something like ubuntu the repos have a older version of node, you can use nvm (https://github.com/creationix/nvm) to have multiple versions and to be able to swtich between them. Also, don't forget to run `npm install` before attempting to run too so that it has the required dependencies

**Comment by LuisS2301** [comment]
I have upgraded to version 6.4.0. now this error again:

/opt/teamspeak-channel/index.js:7
t createClosestChannel = (bot, parentId, username, password, maxAttempts) => {
                                                                           ^
SyntaxError: Unexpected token >
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3

**Comment by Eluinhost** [comment]
Are you sure it's using the correct version on your session? If you're using nvm it requires a relog, you can check with `node --version`

**Comment by LuisS2301** [comment]
Ok, I've reinstalled it again to version 6.5.0 now its working.

ty

**Comment by LuisS2301** [comment]
is it possible to deactivate the channel spam?

**Comment by Eluinhost** [comment]
You mean the ability to make lots of channels quickly? The simplest is to use temporary channels which is the default because then the channel requires a member otherwise it deletes itself. Remember that by default some teamspeak groups have temporary channel delete delay on them which will let them linger around without members

**Comment by LuisS2301** [comment]
and there isn´t an other way?

**Comment by Eluinhost** [comment]
I have an old PHP script running via cron that does some stuff every few minutes on github at UltraSoftcore/uhc-teamspeak-bot

The idle kick part of that script that is what cleans up unused/idle channels in uhc.gg

**Comment by LuisS2301** [comment]
ok this is to complicated.
