### ISSUE TITLE
Can not find module.

### ISSUE THREAD

**Issue by ghost** [Eluinhost/teamspeak-channel-creator#4]
Node Version 6.5

Error code:

```
module.js:457
    throw err;
    ^

Error: Cannot find module 'teamspeak-channel-squatter'
    at Function.Module._resolveFilename (module.js:455:15)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/opt/channel/index.js:1:82)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)

```

**Comment by Eluinhost** [comment]
This will be because you haven't ran `npm install` to install the dependencies first
